version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade --force-reinstall . "awscli>1.20.30"
  
  build:
    commands:
      - python pipelines/upload_code.py --code-repository-name $code_repository_name --bucket $TEMPLATE_BUCKET
      - export PYTHONUNBUFFERED=TRUE
      - export SAGEMAKER_PROJECT_NAME_ID="${SAGEMAKER_PROJECT_NAME}-${SAGEMAKER_PROJECT_ID}"
      - |
        run-pipeline --module-name pipelines.ncf.pipeline \
          --role-arn $SAGEMAKER_PIPELINE_ROLE_ARN \
          --kwargs "{\"region\":\"${AWS_REGION}\",\"sagemaker_project_arn\":\"${SAGEMAKER_PROJECT_ARN}\",\"role\":\"${SAGEMAKER_PIPELINE_ROLE_ARN}\",\"default_bucket\":\"${TEMPLATE_BUCKET}\",\"pipeline_name\":\"${SAGEMAKER_PIPELINE_NAME}\",\"model_package_group_name\":\"${SAGEMAKER_PIPELINE_NAME}\",\"s3_input_data_uri\":\"${s3_input_data_uri}\",\"project_prefix\":\"${project_prefix}\",\"base_job_prefix\":\"${SAGEMAKER_PIPELINE_NAME}\"}"
      - echo "Create/Update of the SageMaker Pipeline and execution completed."

