AWSTemplateFormatVersion: '2010-09-09'
Description: 'SageMaker MLOps HOL CloudFormation Template - IAM roles and SageMaker Notebook'
Resources:
  NotebookInstance:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: "ml.g4dn.xlarge"
      DirectInternetAccess: "Enabled"
      NotebookInstanceName: "MLOPS-Notebook"
      PlatformIdentifier: "notebook-al2-v2"
      RoleArn: !GetAtt SageMakerRole.Arn
      VolumeSizeInGB: 100
  SageMakerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MLOps-SageMakerRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AWSCodeCommitFullAccess"
        - "arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess"
        - "arn:aws:iam::aws:policy/AWSLambda_FullAccess"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - sagemaker.amazonaws.com
            - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
  
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MLOps-CodeBuildRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AWSCodeCommitFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchFullAccess"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AWSLambda_FullAccess"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
            - sagemaker.amazonaws.com
            - lambda.amazonaws.com
          Action:
            - sts:AssumeRole

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MLOps-CodePipelineRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AWSCodeCommitFullAccess"
        - "arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeDeployFullAccess"
        - "arn:aws:iam::aws:policy/AWSLambda_FullAccess"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
            - codepipeline.amazonaws.com
            - lambda.amazonaws.com
          Action:
            - sts:AssumeRole

  LambdaDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MLOps-LambdaDeploymentRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
            - sts:AssumeRole

  EventBridgeRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: MLOps-EventBridgeRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "EventBridgeExecPolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action: "codepipeline:StartPipelineExecution"
            Resource: "*"
      Roles: 
        - Ref: "EventBridgeRole"
