version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade --force-reinstall . "awscli>1.20.30"
  
  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - |
        run-pipeline --module-name pipelines.ncf.pipeline \
          --role-arn $SAGEMAKER_PIPELINE_ROLE_ARN \
          --kwargs "{\"region\":\"${AWS_REGION}\",\"role\":\"${SAGEMAKER_PIPELINE_ROLE_ARN}\",\"default_bucket\":\"${TEMPLATE_BUCKET}\",\"pipeline_name\":\"${SAGEMAKER_PIPELINE_NAME}\",\"model_package_group_name\":\"${model_package_group_name}\",\"s3_input_data_uri\":\"${s3_input_data_uri}\",\"project_prefix\":\"${project_prefix}\",\"inference_image_uri\":\"${inference_image_uri}\",\"base_job_prefix\":\"${SAGEMAKER_PIPELINE_NAME}\"}"
      - echo "Create/Update of the SageMaker Pipeline and execution completed."

